## To Run through ansible
###  ansible-playbook -i nat-server-inventory.yaml wazuh-install.yml
---
- hosts: all
  become: yes
  vars:
    wazuh_manager_ip: "135.181.93.69"

  tasks:
    - name: Download Wazuh agent .deb package
      ansible.builtin.get_url:
        url: https://packages.wazuh.com/4.x/apt/pool/main/w/wazuh-agent/wazuh-agent_4.8.1-1_amd64.deb
        dest: /home/wazuh-agent_4.8.1-1_amd64.deb

    - name: Install Wazuh agent
      ansible.builtin.shell: |
        sudo WAZUH_MANAGER='{{ wazuh_manager_ip }}' WAZUH_AGENT_NAME='{{ ansible_hostname }}' dpkg -i /home/wazuh-agent_4.8.1-1_amd64.deb && sudo systemctl daemon-reload && sudo systemctl enable wazuh-agent && sudo systemctl start wazuh-agent
      args:
        executable: /bin/bash
